name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerdemo:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dockerdemo:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dockerdemo:buildcache,mode=max

      - name: upload server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_ACCESS_TOKEN }}
          script: |
            docker image rm -f ${{ secrets.DOCKER_HUB_USERNAME }}/dockerdemo
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker stop dockerdemo
            docker rm dockerdemo
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dockerdemo
            docker run -d --name dockerdemo -p 5000:80 ${{ secrets.DOCKER_HUB_USERNAME }}/dockerdemo
